name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t tigaplus:latest .
          docker save tigaplus:latest | gzip > tigaplus.tar.gz

      - name: Upload Docker image to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP_TIGAPLUS }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY_TIGAPLUS }}
          source: "tigaplus.tar.gz"
          target: "/root"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP_TIGAPLUS }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY_TIGAPLUS }}
          script: |
            cd /root
            docker load < tigaplus.tar.gz || true
            docker stop tigaplus || true
            docker rm -f tigaplus || true
            sleep 2
            docker run -d -p 80:80 -p 443:443 --name tigaplus tigaplus:latest